services:
  medods_postgres:
    container_name: medods_postgres
    image: "postgres:16"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "root"
      PGDATA: "/data/postgres"
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 5s
      timeout: 5s
      retries: 5

  medods_golang:
    container_name: medods_golang
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      medods_postgres:
        condition: service_healthy

