server:
  host: "0.0.0.0"
  port: 8000
  access_token_lifetime_seconds: 600 # (10 min)
  refresh_token_lifetime_hours: 24



logger:
  level: debug

  format: json

  output:
    type: stdout
    path: ./logs/service.log
    max_size: 10
    max_backups: 3
    max_age: 7
    compress: true


notificator:
  new_ip: "https://webhook.site/ab165bb4-1c1b-4fbe-94aa-80c94fd9c207"